window.FOOD_MAP_DATA = {
  destinations: [
    {
      id: "chongqing",
      label: "重庆",
      country: "中国",
      region: "重庆",
      center: [29.56, 106.55],
      note: "重庆单店和片区清单"
    },
    {
      id: "chengdu-sichuan",
      label: "四川/成都",
      country: "中国",
      region: "四川",
      center: [30.66, 104.06],
      note: "按成都片区录入的四川清单"
    }
  ],
  items: [
    {
      id: "cq-changan-hospital-breakfast",
      destination: "chongqing",
      title: "长安医院住院部门口早餐摊",
      name: "重庆三博长安医院住院部A区",
      lat: 29.576461,
      lng: 106.551353,
      category: "snack",
      confidence: "low",
      address: "建新东路65号重庆三博长安医院附近",
      note: "早餐摊未查到固定店铺，先标住院部附近。"
    },
    {
      id: "cq-liaojia-oil-tea",
      destination: "chongqing",
      title: "廖家妹油茶",
      name: "廖家妹油茶店",
      lat: 29.487575,
      lng: 106.49293,
      category: "snack",
      confidence: "high",
      address: "大渡口区跃进路27号",
      note: "油茶。"
    },
    {
      id: "cq-xiexiaolu-rice-ball",
      destination: "chongqing",
      title: "谢小路糯米团",
      name: "谢小路",
      lat: 29.519655,
      lng: 106.512662,
      category: "snack",
      confidence: "low",
      address: "九龙坡区谢小路附近",
      note: "小摊名未查到固定门牌，先标谢小路路段。"
    },
    {
      id: "cq-wuji-douhua-noodle",
      destination: "chongqing",
      title: "吴记豆花面",
      name: "吴记豆花面总店",
      lat: 29.523855,
      lng: 106.516916,
      category: "snack",
      confidence: "high",
      address: "九龙坡区谢家湾正街19号附25号",
      note: "豆花面。"
    },
    {
      id: "cq-yundougao-shaobing",
      destination: "chongqing",
      title: "熨斗糕老烧饼",
      name: "熨斗糕老烧饼",
      lat: 29.553352,
      lng: 106.570317,
      category: "snack",
      confidence: "high",
      address: "渝中区和平路133号旁边梯坎儿",
      note: "较场口地铁站5号口附近。"
    },
    {
      id: "cq-changshengqiao-market",
      destination: "chongqing",
      title: "长生桥赶场",
      name: "长生桥",
      lat: 29.510924,
      lng: 106.658049,
      category: "place",
      confidence: "low",
      address: "南岸区长生桥镇/长生桥地铁站附近",
      note: "赶场范围不是单一门牌，先标片区中心。"
    },
    {
      id: "cq-shancheng-home-food",
      destination: "chongqing",
      title: "山城家常菜",
      name: "山城家常菜",
      lat: 29.556022,
      lng: 106.578494,
      category: "meal",
      confidence: "high",
      address: "渝中区五一路250号",
      note: "家常菜。"
    },
    {
      id: "cq-laotaipo-feichang-tihua",
      destination: "chongqing",
      title: "老太婆肥肠蹄花",
      name: "老太婆肥肠蹄花汤(晓月店)",
      lat: 29.538646,
      lng: 106.582142,
      category: "meal",
      confidence: "medium",
      address: "南岸区南坪东路585号附18号",
      note: "同名分店较多，这里标南岸晓月店。"
    },
    {
      id: "cq-fanshi-jianghu-food",
      destination: "chongqing",
      title: "樊氏江湖菜",
      name: "樊氏江湖菜(铁板巷店)",
      lat: 29.561082,
      lng: 106.57824,
      category: "meal",
      confidence: "medium",
      address: "渝中区临江支路32号自编号3号附近",
      note: "清单写“梵氏”，公开信息多写作“樊氏”；茄龙、姜丝兔。"
    },
    {
      id: "cq-heida-tu",
      destination: "chongqing",
      title: "黑大兔",
      name: "江湖黑大兔(南滨路旗舰店)",
      lat: 29.517165,
      lng: 106.539707,
      category: "meal",
      confidence: "high",
      address: "南岸区南滨西路2号附35号",
      note: "专做兔。"
    },
    {
      id: "cq-heji-huobao",
      destination: "chongqing",
      title: "和记火爆",
      name: "和记火爆(南滨路店)",
      lat: 29.541567,
      lng: 106.581252,
      category: "meal",
      confidence: "high",
      address: "南岸区海棠溪街道滨江路西段1号",
      note: "火爆菜。"
    },
    {
      id: "cq-chunyang-jiujia",
      destination: "chongqing",
      title: "纯阳酒家",
      name: "纯阳老酒馆·川菜(七星岗店)",
      lat: 29.554631,
      lng: 106.561284,
      category: "meal",
      confidence: "high",
      address: "渝中区观音岩中一支路50号",
      note: "七星岗地铁站附近。"
    },
    {
      id: "cq-xiang-hotpot",
      destination: "chongqing",
      title: "响火锅",
      name: "渝味响火锅(总店)",
      lat: 29.540188,
      lng: 106.511439,
      category: "hotpot",
      confidence: "high",
      address: "渝中区大坪正街124-1-2号",
      note: "大坪总店。"
    },
    {
      id: "cq-changxu-chuanchuan",
      destination: "chongqing",
      title: "长旭大牛串串",
      name: "长旭大牛串串(大堰直营老店)",
      lat: 29.490381,
      lng: 106.497853,
      category: "hotpot",
      confidence: "high",
      address: "大渡口区跃进路587号-593号",
      note: "串串。"
    },
    {
      id: "cq-jinghua-douhua-fish",
      destination: "chongqing",
      title: "精华黑豆花蛙鱼",
      name: "精华黑豆花美蛙鱼自助(万豪酒店国贸中心店)",
      lat: 29.555178,
      lng: 106.574244,
      category: "hotpot",
      confidence: "high",
      address: "渝中区青年路77号LG11室",
      note: "黑豆花美蛙鱼。"
    },
    {
      id: "cq-crispy-chicken",
      destination: "chongqing",
      title: "古法脆皮烧鸡",
      name: "古法脆皮烧鸡(紫荆广场店)",
      lat: 29.588994,
      lng: 106.533728,
      category: "meal",
      confidence: "high",
      address: "两江新区红黄路127号附3-11",
      note: "烧鸡。"
    },
    {
      id: "cq-leijia-laonongmin",
      destination: "chongqing",
      title: "雷家老农民",
      name: "雷家老农民非遗酸辣粉(三峡广场一店)",
      lat: 29.557229,
      lng: 106.462115,
      category: "snack",
      confidence: "high",
      address: "沙坪坝区渝碚路30-23号",
      note: "酸辣粉、凉面。"
    },
    {
      id: "cq-yage-taro",
      destination: "chongqing",
      title: "亚歌芋圆",
      name: "亚歌的芋圆(观音桥店)",
      lat: 29.577744,
      lng: 106.538783,
      category: "sweet",
      confidence: "high",
      address: "两江新区塔坪路55号北仓文创园6-5",
      note: "芋圆。"
    },
    {
      id: "cq-pangzi-snack",
      destination: "chongqing",
      title: "胖子小吃",
      name: "胖子小吃(炫地7街店)",
      lat: 29.557607,
      lng: 106.46001,
      category: "snack",
      confidence: "medium",
      address: "沙坪坝区三峡广场地下购物中心I区35号",
      note: "同名较多，这里标重师/炫地7街一带的胖子小吃。"
    },
    {
      id: "cq-ouwang-chaoshou",
      destination: "chongqing",
      title: "藕王抄手",
      name: "重庆大学B区正门附近",
      lat: 29.568981,
      lng: 106.462187,
      category: "snack",
      confidence: "low",
      address: "沙坪坝区重庆大学B区门口附近",
      note: "只查到“重大B区门口左侧”的线索，先标校门。"
    },
    {
      id: "cq-xiulan-noodle",
      destination: "chongqing",
      title: "秀兰面店坊",
      name: "秀兰面点坊",
      lat: 29.566108,
      lng: 106.463738,
      category: "snack",
      confidence: "high",
      address: "沙坪坝区正街124号",
      note: "面点。"
    },
    {
      id: "cq-xiangji-grilled-fish",
      destination: "chongqing",
      title: "向记独一味烤鱼",
      name: "向记独一味古法烤鱼(总店)",
      lat: 29.561252,
      lng: 106.530066,
      category: "meal",
      confidence: "high",
      address: "两江新区金源路66号附3号",
      note: "烤鱼。"
    },
    {
      id: "cq-ahui-chicken",
      destination: "chongqing",
      title: "阿辉黔江鸡杂",
      name: "阿辉黔江鸡杂(解放碑店)",
      lat: 29.558367,
      lng: 106.575191,
      category: "meal",
      confidence: "high",
      address: "渝中区邹容路114号来龙巷",
      note: "黔江鸡杂。"
    },
    {
      id: "cq-pengnana-miliangxia",
      destination: "chongqing",
      title: "彭娜娜米凉虾",
      name: "彭娜娜米凉虾(爱琴海店)",
      lat: 29.642359,
      lng: 106.546276,
      category: "sweet",
      confidence: "high",
      address: "两江新区金州大道30号附4号",
      note: "米凉虾。"
    },
    {
      id: "cq-ganpopo-tangyuan",
      destination: "chongqing",
      title: "甘婆婆醪糟汤圆",
      name: "甘婆婆醪糟汤圆",
      lat: 29.5512,
      lng: 106.594128,
      category: "sweet",
      confidence: "high",
      address: "南岸区上新街54号",
      note: "黑米凉糕、醪糟汤圆。"
    },
    {
      id: "cq-sanyangzi",
      destination: "chongqing",
      title: "三样子",
      name: "三样子(弹子石总店)",
      lat: 29.584517,
      lng: 106.592896,
      category: "sweet",
      confidence: "medium",
      address: "南岸区群慧路21号",
      note: "同名分店较多，这里标弹子石总店。"
    },
    {
      id: "cq-nameless-douhua",
      destination: "chongqing",
      title: "无名豆花",
      name: "无名豆花",
      lat: 29.555857,
      lng: 106.572636,
      category: "meal",
      confidence: "high",
      address: "渝中区大同巷11号",
      note: "豆花饭。"
    },
    {
      id: "cq-chenxiang",
      destination: "chongqing",
      title: "尘香",
      name: "尘香·传统川菜(创汇首座店)",
      lat: 29.553872,
      lng: 106.577847,
      category: "meal",
      confidence: "high",
      address: "渝中区新华路388号创汇首座LG层",
      note: "人均约100的餐厅。"
    },
    {
      id: "cq-ring-mall-forest",
      destination: "chongqing",
      title: "光环购物公园 悬浮森林",
      name: "沐光森林",
      lat: 29.649382,
      lng: 106.528951,
      category: "place",
      confidence: "high",
      address: "两江新区湖彩路118号",
      note: "光环购物公园内，重光地铁站附近。"
    },
    {
      id: "cq-lou-bbq",
      destination: "chongqing",
      title: "陋烧烤",
      name: "陋烧烤",
      lat: 29.649795,
      lng: 106.523068,
      category: "hotpot",
      confidence: "high",
      address: "两江新区湖红路415号附57号",
      note: "烧烤。"
    },
    {
      id: "cq-sanmei-noodle",
      destination: "chongqing",
      title: "三妹面庄",
      name: "三妹面庄(学府雅居店)",
      lat: 29.499999,
      lng: 106.572329,
      category: "snack",
      confidence: "medium",
      address: "南岸区龙景苑东南门旁",
      note: "南岸面馆同名较多，这里标学府雅居店。"
    },
    {
      id: "cq-linhua-noodle",
      destination: "chongqing",
      title: "临华老面馆",
      name: "临华老面馆",
      lat: 29.556277,
      lng: 106.561287,
      category: "snack",
      confidence: "high",
      address: "渝中区临华路55号",
      note: "渝中区面馆。"
    },
    {
      id: "cq-shancheng-lamb",
      destination: "chongqing",
      title: "山城羊肉馆",
      name: "山城羊肉馆(阳光星座店)",
      lat: 29.554907,
      lng: 106.573677,
      category: "meal",
      confidence: "high",
      address: "渝中区民生路9号阳光星座3楼",
      note: "渝中区羊肉馆。"
    },
    {
      id: "cq-yeshuigou",
      destination: "chongqing",
      title: "野水沟",
      name: "华新街野水沟社区",
      lat: 29.572654,
      lng: 106.536641,
      category: "place",
      confidence: "low",
      address: "华新街中野路与建新东路交叉口附近",
      note: "烧白、炒鸡、拌菜等为片区/市场型吃法，先标野水沟社区。"
    },
    {
      id: "cq-tiaotiao-ciba",
      destination: "chongqing",
      title: "挑挑糍粑",
      name: "华新街地铁站",
      lat: 29.563956,
      lng: 106.537132,
      category: "snack",
      confidence: "low",
      address: "华新街地铁站出口附近",
      note: "按“地铁站口/天桥下”线索标点，小摊位置会变。"
    },
    {
      id: "cq-liruotao",
      destination: "chongqing",
      title: "李若桃",
      name: "李若桃·手作酸奶铺(观音桥步行街店)",
      lat: 29.57362,
      lng: 106.533083,
      category: "sweet",
      confidence: "high",
      address: "观音桥步行街1期1-14",
      note: "饮品。"
    },
    {
      id: "cq-douji-milk-tea",
      destination: "chongqing",
      title: "豆吉汤圆奶茶",
      name: "豆吉汤圆奶茶(凯旋路电梯店)",
      lat: 29.552009,
      lng: 106.576625,
      category: "sweet",
      confidence: "high",
      address: "渝中区凯旋路电梯附近",
      note: "饮品。"
    },
    {
      id: "cq-puniang-sugar",
      destination: "chongqing",
      title: "璞孃食糖",
      name: "璞孃食糖(黄泥磅店)",
      lat: 29.595014,
      lng: 106.534505,
      category: "sweet",
      confidence: "high",
      address: "两江新区黄泥磅紫园路49号",
      note: "港风糖水。"
    },
    {
      id: "cd-niushikou",
      destination: "chengdu-sichuan",
      title: "牛市口",
      name: "牛市口片区",
      lat: 30.64187,
      lng: 104.103264,
      category: "place",
      confidence: "low",
      address: "成都市锦江区牛市口附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "周记糕点（无糖麻薯、米老鼠）",
        "家常味",
        "私房水饺",
        "伍妹烤鸭（再往里走还有回味叔叔冒烤鸭）",
        "poojpooji",
        "1985牛市口番茄煎蛋面",
        "堂口原味老火锅（也可试串串香；龙户人家肉里夹蒜蓉）",
        "朋友推荐：落舌冒菜、天星正源火锅、铁门杂酱面"
      ]
    },
    {
      id: "cd-hongji-xinlu",
      destination: "chengdu-sichuan",
      title: "宏济新路",
      name: "宏济新路片区",
      lat: 30.641597,
      lng: 104.094139,
      category: "place",
      confidence: "low",
      address: "成都市锦江区宏济新路附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "油条豆浆（窝子油糕、糍粑块）",
        "泸州小笼包",
        "热活面包"
      ]
    },
    {
      id: "cd-fuqin",
      destination: "chengdu-sichuan",
      title: "抚琴（早市+夜市）",
      name: "抚琴片区",
      lat: 30.677314,
      lng: 104.042105,
      category: "place",
      confidence: "low",
      address: "成都市金牛区抚琴附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "朱碧琼肥肠粉",
        "军屯锅盔",
        "丹棱大雅油冻粑",
        "黄记品皮车手提串串香"
      ]
    },
    {
      id: "cd-tuqiao-majiachang-wenjiang",
      destination: "chengdu-sichuan",
      title: "土桥 ↔ 马家场 ↔ 温江",
      name: "成都西郊片区",
      lat: 30.707,
      lng: 103.951,
      category: "place",
      confidence: "low",
      address: "土桥、马家场、温江一线",
      note: "跨度较大，点位先放在土桥/马家场/温江中间。",
      recommendations: [
        "顺记腌卤",
        "席家羊肉卤",
        "雅琪口腔门口下午串串摊、板前料理",
        "土桥369赶场",
        "马家场晶晶兔鲜火锅",
        "黄粱茶烤铺",
        "马家场老街胖娃肥肠粉",
        "彭记蛋烘糕（排队长，用料扎实）",
        "兴隆街高记蛋烘糕（也可以，不排队）",
        "牟炒手",
        "老温江白开水鹅婆婆传统小吃"
      ]
    },
    {
      id: "cd-century-city-zhonghe",
      destination: "chengdu-sichuan",
      title: "世纪城 ↔ 中和",
      name: "世纪城/中和片区",
      lat: 30.5573,
      lng: 104.0863,
      category: "place",
      confidence: "low",
      address: "世纪城到中和一线",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "乔一乔怪味餐厅（本地朋友带吃，确实不错）",
        "悦百味",
        "中和兔火锅餐厅很多"
      ]
    },
    {
      id: "cd-drinks",
      destination: "chengdu-sichuan",
      title: "成都饮品清单",
      name: "成都饮品",
      lat: 30.657,
      lng: 104.066,
      category: "sweet",
      confidence: "low",
      address: "成都市区，多店/多片区",
      note: "饮品多为连锁或多点位，先放在市中心。",
      recommendations: [
        "菊乐打牛奶啰",
        "李若桃手作酸奶",
        "锦城吃茶",
        "树夏",
        "引悦茶",
        "福发发"
      ]
    },
    {
      id: "cd-dongguang-fanyue",
      destination: "chengdu-sichuan",
      title: "东光 ↔ 泛悦国际",
      name: "东光/泛悦国际片区",
      lat: 30.6152,
      lng: 104.0891,
      category: "place",
      confidence: "low",
      address: "锦江区东光到武侯区泛悦国际一带",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "幺怪面（对面甜皮鸭也好吃）",
        "酥香居叶儿粑",
        "源源小吃店",
        "焱味邱金"
      ]
    },
    {
      id: "cd-financial-city-xinxi",
      destination: "chengdu-sichuan",
      title: "金融城站 ↔ 新熙大道",
      name: "金融城片区",
      lat: 30.582579,
      lng: 104.064147,
      category: "place",
      confidence: "low",
      address: "金融城地铁站附近；新熙大道位置待核",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "南亭茶月·花椒文化餐厅",
        "basdban",
        "热晨烘焙（推荐但这次没来得及去）",
        "宜宾中渡口面王（新熙大道）"
      ]
    },
    {
      id: "cd-wenshuyuan",
      destination: "chengdu-sichuan",
      title: "文殊院",
      name: "文殊院片区",
      lat: 30.675418,
      lng: 104.072527,
      category: "place",
      confidence: "low",
      address: "成都市青羊区文殊院附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "宫廷糕点",
        "严太婆锅盔",
        "洞子口张老二凉粉",
        "省医院的张老五凉粉也有人推荐"
      ]
    },
    {
      id: "cd-renmin-park",
      destination: "chengdu-sichuan",
      title: "人民公园",
      name: "人民公园片区",
      lat: 30.65699,
      lng: 104.057641,
      category: "place",
      confidence: "low",
      address: "成都市青羊区小南街8号附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "熊猫邮局（成都有好几家，可以集熊猫邮戳）",
        "喝盖碗茶看变脸",
        "锦江剧场表演"
      ]
    },
    {
      id: "cd-caotang-north-road",
      destination: "chengdu-sichuan",
      title: "草堂北路",
      name: "草堂北路片区",
      lat: 30.666031,
      lng: 104.029117,
      category: "place",
      confidence: "low",
      address: "成都市青羊区草堂北路附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "乐山鲜知味钵钵鸡"
      ]
    },
    {
      id: "cd-baiguolin",
      destination: "chengdu-sichuan",
      title: "白果林",
      name: "白果林片区",
      lat: 30.673851,
      lng: 104.033278,
      category: "place",
      confidence: "low",
      address: "成都市金牛区白果林地铁站附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "喜三姨老火锅"
      ]
    },
    {
      id: "cd-orthopedic-hospital",
      destination: "chengdu-sichuan",
      title: "省骨科医院",
      name: "四川省骨科医院武侯院区附近",
      lat: 30.650947,
      lng: 104.040182,
      category: "place",
      confidence: "low",
      address: "武侯区一环路西一段132号附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "胡二哥药膳蹄花"
      ]
    },
    {
      id: "cd-cuqiao",
      destination: "chengdu-sichuan",
      title: "簇桥",
      name: "簇桥片区",
      lat: 30.60767,
      lng: 103.989923,
      category: "place",
      confidence: "low",
      address: "成都市武侯区簇桥附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "豆腐脑花",
        "戴鸭子"
      ]
    },
    {
      id: "cd-kuanzhai",
      destination: "chengdu-sichuan",
      title: "宽窄巷子",
      name: "宽窄巷子片区",
      lat: 30.663869,
      lng: 104.053307,
      category: "place",
      confidence: "low",
      address: "成都市青羊区宽窄巷子附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "pinocchio gelateria",
        "轩轩小院",
        "熊猫文创饰品",
        "谷悟面包",
        "纯阳面馆",
        "坎尖老火锅"
      ]
    },
    {
      id: "cd-yulin",
      destination: "chengdu-sichuan",
      title: "玉林",
      name: "玉林片区",
      lat: 30.626936,
      lng: 104.06228,
      category: "place",
      confidence: "low",
      address: "成都市武侯区玉林街附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "名小吃",
        "北方面食坊",
        "berge bakery",
        "花花串串",
        "谭家钵钵鸡"
      ]
    },
    {
      id: "cd-xiaojiahe",
      destination: "chengdu-sichuan",
      title: "肖家河",
      name: "肖家河片区",
      lat: 30.630661,
      lng: 104.043628,
      category: "place",
      confidence: "low",
      address: "成都市武侯区肖家河附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "肖家河家常面",
        "天香麻手菜",
        "永乐饭店（排队人特别多）",
        "皇城坝牛肉",
        "毛家鸡杂火锅",
        "罗姐竹笋芋儿鸡"
      ]
    },
    {
      id: "cd-jianshe-road",
      destination: "chengdu-sichuan",
      title: "建设路",
      name: "建设路片区",
      lat: 30.667229,
      lng: 104.097153,
      category: "place",
      confidence: "low",
      address: "成都市成华区建设路附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "半天烤鱼面（红糖锅盔）",
        "同签签锅巴土豆",
        "胡记小吃店",
        "胖千千八二干海椒抄手"
      ]
    },
    {
      id: "cd-xinhua-community",
      destination: "chengdu-sichuan",
      title: "新华社区",
      name: "新华社区片区",
      lat: 30.65766,
      lng: 104.109166,
      category: "place",
      confidence: "low",
      address: "成都市成华区新华社区附近",
      note: "四川截图清单，按片区点位录入。",
      recommendations: [
        "刘林林米凉虾",
        "卢氏铁板烧",
        "笠笠芋圆凉水",
        "愿琪堂·棚棚老火锅"
      ]
    }
  ]
};
